DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS pet;
DROP TABLE IF EXISTS petaction;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE pet(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  hungerLevel INTEGER DEFAULT 50,
  happinessLevel INTEGER DEFAULT 50,
  energyLevel INTEGER DEFAULT 50,
  status TEXT DEFAULT 'Average',
  lastInteraction TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  userID INTEGER NOT NULL,
  FOREIGN KEY (userID) REFERENCES user(id)
);

CREATE TABLE petAction (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actionType TEXT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  petID INTEGER NOT NULL,
  userID INTEGER NOT NULL,
  FOREIGN KEY (petID) REFERENCES pet(id),
  FOREIGN KEY (userID) references user(ID)
);